accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_view
from .views import register

urlpatterns = [
    path('login/', auth_view.LoginView.as_view(), name='login'),
    path('logout/', auth_view.LogoutView.as_view(template_name='registration/logout.html'), name='logout'),
    path('register/', register, name='register'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('photo.urls')),
    path('accounts/', include('accounts.urls'))
]

from django.conf.urls.static import static
from django.conf import settings

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

photo/urls.py
from django.urls import path
from django.views.generic.detail import DetailView

from .views import *
from .models import Photo

app_name = 'photo'

urlpatterns = [
    path('', photo_list, name='photo_list'),
    path('detail/<int:pk>/', DetailView.as_view(model=Photo, template_name='photo/detail.html'),
         name='photo_detail'),
    path('upload/', PhotoUploadView.as_view(), name='photo_upload'),
    path('delete/<int:pk>/', PhotoDeleteView.as_view(), name='photo_delete'),
    path('update/<int:pk>/', PhotoUpdateView.as_view(), name='photo_update'),
]

accounts/models.py
from django.db import models

# Create your models here.

photo/models.py
from django.db import models

from django.contrib.auth.models import User
from django.urls import reverse


# Create your models here.

class Photo(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_photos')


    photo = models.ImageField(upload_to='photos/%Y/%m/%d', default='photos/no_image.png')
    text = models.TextField()

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-updated']

    def __str__(self):
        return self.author.username + " " + self.created.strftime("%Y-%m-%d %H:%M:%S")

    def get_absolute_url(self):
         return reverse('photo:photo_detail', args=[str(self.id)])

accounts/forms.py
from django.contrib.auth.models import User
from django import forms

class RegisterForm(forms.ModelForm):
    password = forms.CharField(label='비밀번호', widget=forms.PasswordInput)
    password2 = forms.CharField(label='비밀번호 재입력', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email']

    def clean_password2(self):
        cd = self.changed_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('비밀번호가 일치하지 않습니다!')
        return cd['password2']

accounts/views.py
from django.shortcuts import render
from .forms import RegisterForm

def register(request):

    if request.method == 'POST':
        user_form = RegisterForm(request.POST)

        if user_form.is_vaild():
            new_user = user_form.save(commit=False)
            new_user.set_password(user_form.cleanded_data['password'])
            new_user.save()
            return render(request, 'registration/register_done.html', {'new_user':new_user})

    else:
        user_form = RegisterForm()

    return render(request, 'registration/register.html', {'form':user_form})

# Create your views here.

photo/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from .models import Photo
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin


# Create your views here.

@login_required
def photo_list(request):
    photos = Photo.objects.all()
    return render(request, 'photo/list.html', {'photos': photos})


class PhotoUploadView(LoginRequiredMixin, CreateView):
    model = Photo
    fields = ['photo', 'text']
    template_name = 'photo/upload.html'


    def form_valid(self, form):
        form.instance.author_id = self.request.user.id
        if form.is_valid():
            form.instance.save()
            return redirect('/')
        else:
            return self.render_to_response({'form': form})

class PhotoDeleteView(LoginRequiredMixin, DeleteView):
    model = Photo
    success_url = '/'
    template_name = 'photo/delete.html'


class PhotoUpdateView(LoginRequiredMixin, UpdateView):
    model = Photo
    fields = ['photo', 'text']
    template_name = 'photo/update.html'

photo/templates/photo/delete.html
{% extends 'base.html' %} 
{% block title %}- Delete{% endblock %} 
 
{% block content %} 
<div class="row"> 
    <div class="col-md-2"></div> 
    <div class="col-md-8 panel panel-default"> 
        <div class="alert alert-info"> 
            Do you want to delete {{object}}? 
        </div> 
        <form action="" method="post"> 
             {{form.as_p}} 
             {% csrf_token %} 
            <input type="submit" class="btn btn-danger" value="Confirm"> 
        </form> 
    </div> 
    <div class="col-md-2"></div> 
</div> 
{% endblock %} 

photo/templates/photo/detail.html
{% extends 'base.html' %} 
{% block title %} 
     {{object.text|truncatechars:10}} 
{% endblock %} 
 
{% block content %}
    <div class="row">
            <div class="col-md-2"></div>
            <div class="col-md-8 panel panel-default">
                <p><img src="{{object.photo.url}}" style="width:100%;"></p>
                <button type="button" class="btn btn-outline-primary btn-sm">
                     {{object.author.username}}</button>
                <p>{{object.text|linebreaksbr}}</p>

                 <a href="{% url 'photo:photo_delete' pk=object.id %}" class="btn btn-outline-danger
btn-sm float-right">Delete</a>
                <a href="{% url 'photo:photo_update' pk=object.id %}" class="btn btn-outline-success
btn-sm float-right">Update</a>
             </div>
            <div class="col-md-2"></div>
    </div>
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8 panel panel-default">
            {% load disqus_tags %}
            {% disqus_show_comments %}
        </div>
        <div class="col-md-2"></div>
    </div>
    

{% endblock %}

photo/templates/photo/list.html
{% extends 'base.html' %} 
 
{% block title %}- List{% endblock %} 
 
{% block content %} 
     {% for post in photos %} 
        <div class="row"> 
            <div class="col-md-2"></div> 
             <div class="col-md-8 panel panel-default"> 
                <p><img src="{{post.photo.url}}" style="width:100%;"></p> 
                <button type="button" class="btn btn-xs btn-info"> 
                     {{post.author.username}}</button> 
                 <p>{{post.text|linebreaksbr}}</p> 
                <p class="text-right"><a href="{% url 'photo:photo_detail' pk=post.id %}" class="btn btn-xs btn-
success">댓글달기</a>
                </p>
            </div>
            <div class="col-md-2"></div>
        </div>

     {% endfor %}
{% endblock %}

photo/templates/photo/update.html
{% extends 'base.html' %} 
{% block title %} 
- Upate 
{% endblock %} 
 
{% block content %} 
<div class="row"> 
    <div class="col-md-2"></div> 
    <div class="col-md-8 panel panel-default"> 
        <form action="" method="post" enctype="multipart/form-data"> 
             {{form.as_p}} 
             {% csrf_token %}
                        <input type="submit" class="btn btn-primary" value="Update">
        </form>
    </div>
    <div class="col-md-2"></div>
</div>
{% endblock %}

photo/templates/photo/upload.html
{% extends 'base.html' %} 
{% block title %}- Upload{% endblock %} 
 
{% block content %} 
<div class="row"> 
    <div class="col-md-2"></div> 
    <div class="col-md-8 panel panel-default"> 
        <form action="" method="post" enctype="multipart/form-data"> 
             {{form.as_p}} 
             {% csrf_token %} 
            <input type="submit" class="btn btn-primary" value="Upload"> 
        </form> 
    </div> 
    <div class="col-md-2"></div>
</div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-
q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
crossorigin="anonymous"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
crossorigin="anonymous"></script>

<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-
ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
crossorigin="anonymous"></script>

    <title>Photogram {% block title %}{% endblock %}</title>
</head>
<body>

<div class="container">
    <header class="header clearfix">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="/">Photogram</a>
            <ul class="nav">
<li class="nav-item"><a href="/" class="active nav-link ">Home</a></li>
                                 {% if user.is_authenticated %}
                <li class="nav-item"><a href="#" class="nav-link">Welcome,
{{user.get_username}}</a></li>
                <li class="nav-item"><a href="{% url 'photo:photo_upload'  %}" class="nav-
link">Upload</a></li>
                <li class="nav-item"><a href="{% url 'logout' %}" class="nav-link">Logout</a></li>
                 {% else %}
                <li class="nav-item"><a href="{% url 'login' %}" class="nav-link">Login</a></li>
                <li class="nav-item"><a href="{% url 'register' %}" class="nav-link">Signup</a></li>
                {% endif %}
            </ul>
        </nav>
    </header>
     {% block content %}
     {% endblock %}

    <footer class="footer">
        <p>&copy; 2020 JWS. Powered By Django</p>
    </footer>
</div>

</body>
</html>